### ISSUE TITLE
[QuickMessages] The button to save a message appears when the text input is blank

### ISSUE THREAD

**Issue by dav1312** [QWERTxD/BetterDiscordPlugins#1]
The result is that is saves the "Message #channel" or "Message @user" which is kinda weird
![image](https://user-images.githubusercontent.com/63931154/106763170-dd2e5380-6636-11eb-8829-9aed7e0fb11d.png)
![image](https://user-images.githubusercontent.com/63931154/106763246-eddec980-6636-11eb-97cb-ad416ac3ff39.png)

**Comment by QWERTxD** [comment]
make sure you’re using v1.0.2
