### ISSUE TITLE
[FEATURE REQUEST] More Activities

### ISSUE THREAD

**Issue by dav1312** [QWERTxD/BetterDiscordPlugins#103]
**Is your feature request related to a problem? Please describe.**
Not having all activities.

**Describe the feature you'd like**
Add `Chess In The Park`, `Checkers In The Park`, `Doodle Crew`, `Word Snacks`, `Letter Tile` and `SpellCast`

**Additional context**
![image](https://user-images.githubusercontent.com/63931154/140381450-c9b436df-a12d-4d86-acbc-50cc04eabfc6.png)

**Comment by EliTheCoder** [comment]
here's a list of all of the ids
https://gist.github.com/GeneralSadaf/42d91a2b6a93a7db7a39208f2d8b53ad

**Comment by dav1312** [comment]
Nice!
![image](https://user-images.githubusercontent.com/63931154/140832666-f33179c3-9343-499f-8f59-af498fc90485.png)
