### ISSUE TITLE
[BUG] Quick toggler causes discord to crash !

### ISSUE THREAD

**Issue by enzomtpYT** [QWERTxD/BetterDiscordPlugins#104]
**Describe the Bug**
Quick toggler causes discord to crash !

**To Reproduce**
Press Ctrl + D to open quick toggler and here a crash !

**Expected Behavior**
Open quick toggler menu
**Screenshots**
![image](https://user-images.githubusercontent.com/40535918/138922989-90d75f91-2563-460d-aee7-8095b4b505ec.png)

**Discord Version**
Stable 102424 (5765f23)
BetterDiscord 1.2.3
Host 1.0.9003 Windows 10 64-Bit (10.0.19043)

**Additional Context**
Plugin version : 1.0.0

All my plugins : 
![image](https://user-images.githubusercontent.com/40535918/138923228-40c51ed4-28c6-40d0-9ecd-0746e6c24715.png)

**Comment by ArcWandx86** [comment]
Not much to contribute but just gonna say that it crashes when I use a non-default keybind as well (ctrl + \`).

**Comment by EconomicSacks** [comment]
Same thing with me

**Comment by DavedZrod** [comment]
man, when is this getting fixed
