### ISSUE TITLE
status becoming invisible after quitting games

### ISSUE THREAD

**Issue by Eegeg** [QWERTxD/BetterDiscordPlugins#116]
When i play a game and then quit it my status becomes invisible even though my status was online before

1. Play any game
2. Quit the game
3. Status was changed from do not disturb to invisible instead of online

It should be the status before do not disturb

Version is: stable, Build Number: 105691, Version Hash: 039634f8b06bf40775fb1a0b570057abbd74d56f

**Comment by christiankek** [comment]
It doesn't make you invisible, it still makes you go online. It just turns your online indicator gray somehow lol

**Comment by Eegeg** [comment]
ok
