### ISSUE TITLE
[BUG] not getting mobile notifications anymore

### ISSUE THREAD

**Issue by SymoHTL** [QWERTxD/BetterDiscordPlugins#126]
So i got this plugin like 3 months ago and since then i dont get mobile notifications anymore. Please help

And yes every setting on my phone is the right i reinstalled discord on my mobile uninstalled betterdiscord once 2 but nothing works

**Comment by MichaelDavidGK** [comment]
Plugins cannot break your notifications on mobile, they only have effect on Discord session/instance you injected them into
