### ISSUE TITLE
[Feature Request] [InAppNotifications] Message Length Based Display Time

### ISSUE THREAD

**Issue by PaxiTheAlchemist** [QWERTxD/BetterDiscordPlugins#13]
# Message Length Based Display Time

## Why I feel this would be a good addition

As someone who uses notifications while doing other things on Discord, as I'm sure all users who use this plugin do, I feel like it would be a beneficial feature for reading those rather longer messages before they disappear. Ever since I switched off from a plugin similar to this one here which had the feature to prolong the display time for bigger messages, I just felt that this plugin was incomplete without this feature.

## Complementary Additions

- An input for minimum and/or maximum display time
  - This input could take the place of the current input for the display time
- An input for the multiplier scale of the length based display time

## Example Implementation

Here is an example of an implementation within the settings menu for the plugin which includes a switch for enabling the feature along with a text area to input the minimum display time.

<div align="center"><p></p><img src="https://i.imgur.com/zjIE1Ij.png"></div>

**Comment by coredev-uk** [comment]
I agree with this, however instead of setting a minimum time or something that gets the length of the message either in pixels (if you can) or by how many words there are and have a multiplier for it that the user can configure that will set the time it is on screen for.
