### ISSUE TITLE
[BUG] AssignBadges construction error

### ISSUE THREAD

**Issue by OmegaBlurz** [QWERTxD/BetterDiscordPlugins#130]
![image](https://user-images.githubusercontent.com/81272128/148653380-ccb866ed-fa53-4808-8cce-c73795bda7b2.png)

**Discord Version**
Canary 110234 (b3cd76f)
BetterDiscord 1.3.0
Windows 10 64-Bit (10.0.19043)

**Comment by OmegaBlurz** [comment]
Recent canary update has also broken some other plugins I have as well as some themes I occasionally use.

**Comment by OmegaBlurz** [comment]
now happening on Stable 110451 (c233a73)

**Comment by Sarreos** [comment]
Happening for me too on stable

**Comment by ProgrammerPython** [comment]
nothing changed yet, crash on Stable 110451 (c233a73)

**Comment by jayjayhejetplane** [comment]
Likewise, although my error message has an extra line:

AssignBadges: Could not be constructed.
    at Object.initializeAddon (<anonymous>:4:307996)
    at Object.loadAddon (<anonymous>:4:269972)
    at Object.loadAddon (<anonymous>:4:307108)
    at Object.reloadAddon (<anonymous>:4:270675)
    at FSWatcher.<anonymous> (<anonymous>:4:267865)

**Comment by banana074** [comment]
i have only 4 
![image](https://user-images.githubusercontent.com/96134797/150200568-03878baa-df8a-49d8-b994-7e144bd0dd39.png)

**Comment by OmegaBlurz** [comment]
#151

**Comment by OmegaBlurz** [comment]
Actually I'll keep open until pushed
