### ISSUE TITLE
[BUG]TYPING USER AVATARS BROKEN

### ISSUE THREAD

**Issue by R1see** [QWERTxD/BetterDiscordPlugins#131]
![image](https://user-images.githubusercontent.com/62443062/149292222-1e5532df-eab3-4033-8cb0-2eb442dd2002.png)

**Comment by TBIN7** [comment]
Its broken after discords internal update which broke alot of things

**Comment by TBIN7** [comment]
@QWERTxD

**Comment by rangerAMG** [comment]
ok so i fixed it by running it through  [a website which fixes discord css stuff](https://laynetheepic.github.io/projects/pc-theme-converter/)

the fixed one in the zip file should work (github won't let me upload the js file, only a zip)

[TypingUsersAvatars.plugin.js.zip](https://github.com/QWERTxD/BetterDiscordPlugins/files/7861541/TypingUsersAvatars.plugin.js.zip)

**Comment by TBIN7** [comment]
@rangerAMG Thanks you so much Luv u <3

**Comment by BlueStarBRS** [comment]
@QWERTxD fix it pls @rangerAMG have maybe helped you

**Comment by MichaelDavidGK** [comment]
it's fixed, update plugin 

> @QWERTxD fix it pls @rangerAMG have maybe helped you

**Comment by BlueStarBRS** [comment]
> it's fixed, update plugin
> 
> > @QWERTxD fix it pls @rangerAMG have maybe helped you

it says no update avaible so ... where ? thx

**Comment by MichaelDavidGK** [comment]
> 
> it says no update avaible so ... where ? thx

you can download from github repo (right press on raw and save link as):
![image](https://user-images.githubusercontent.com/39009683/150863708-b0f76c92-87c1-4262-b472-327e64f6254b.png)

**Comment by BlueStarBRS** [comment]
> > it says no update avaible so ... where ? thx
> 
> you can download from github repo (right press on raw and save link as)

thx and now it only a update for plugin repo and its all up to date (on repo you can only find the brocken one)

**Comment by BlueStarBRS** [comment]
> ok so i fixed it by running it through [a website which fixes discord css stuff](https://laynetheepic.github.io/projects/pc-theme-converter/)
> 
> the fixed one in the zip file should work (github won't let me upload the js file, only a zip)
> 
> [TypingUsersAvatars.plugin.js.zip](https://github.com/QWERTxD/BetterDiscordPlugins/files/7861541/TypingUsersAvatars.plugin.js.zip)

i swear i love you for this tipp bro

**Comment by BlueStarBRS** [comment]
@RadNotRed fixed by owner ?
