### ISSUE TITLE
[BUG] GrammarCorrect not working, after discord update

### ISSUE THREAD

**Issue by GAbO1254** [QWERTxD/BetterDiscordPlugins#133]
**Describe the Bug**
After the latest update (that broke a lot of stuff like themes) the other day, the option for grammar correction is missing from the context menu. At startup, the plugin shows up as loaded, but even after system restart it still doesn't work.

**To Reproduce**
be on the most recent version of BD

**Expected Behavior**

**Screenshots**
https://i.imgur.com/KRD23Jo.png

**Discord Version**
Stable 110451 (c233a73)
BetterDiscord 1.3.0
Host 1.0.9003 Windows 10 64-Bit (10.0.19042)

**Additional Context**
loaded plugins:
https://i.imgur.com/ATuP0Qp.png

**Comment by MichaelDavidGK** [comment]
Fixed:
https://github.com/QWERTxD/BetterDiscordPlugins/pull/143

**Comment by Xzer0o0** [comment]
it's broken again
