### ISSUE TITLE
[BUG] QuickMessages not working on startup

### ISSUE THREAD

**Issue by StepCenta** [QWERTxD/BetterDiscordPlugins#134]
**Describe the Bug**
When opening BD the app will load the plugins but right clicking on the message box won't show saved quick messages. To fix this issue you have to manually deactivate and reactivate the plugin every startup.

**To Reproduce**
Open BetterDiscord and right click on the message box.

**Expected Behavior**
Quick Messages tab should appear when right clicking.

**Discord Version**
Stable 110451 (c233a73)
Better Discord 1.3.0

**Comment by MichaelDavidGK** [comment]
Adding logs:

Uncaught (in promise) TypeError: Cannot read property 'buildMenuItem' of undefined
    at QuickMessages.plugin.js:171
    at Array.forEach (<anonymous>)
    at QuickMessages.patchTextAreaContextMenus (QuickMessages.plugin.js:169)
    at QuickMessages.onStart (QuickMessages.plugin.js:145)
    at QuickMessages.start (0PluginLibrary.plugin.js:4352)
    at Object.startPlugin (<anonymous>:4:309140)
    at Object.startAddon (<anonymous>:4:308935)
    at Object.loadAddon (<anonymous>:4:270124)
    at Object.loadAddon (<anonymous>:4:307108)
    at Object.loadAllAddons (<anonymous>:4:272224)
    at Object.initialize (<anonymous>:4:266714)
    at Object.initialize (<anonymous>:4:306318)
    at Object.startup (<anonymous>:4:368333)

**Comment by StepCenta** [comment]
> Adding logs:
> 
> ```
> Uncaught (in promise) TypeError: Cannot read property 'buildMenuItem' of undefined
>     at QuickMessages.plugin.js:171
>     at Array.forEach (<anonymous>)
>     at QuickMessages.patchTextAreaContextMenus (QuickMessages.plugin.js:169)
>     at QuickMessages.onStart (QuickMessages.plugin.js:145)
>     at QuickMessages.start (0PluginLibrary.plugin.js:4352)
>     at Object.startPlugin (<anonymous>:4:309140)
>     at Object.startAddon (<anonymous>:4:308935)
>     at Object.loadAddon (<anonymous>:4:270124)
>     at Object.loadAddon (<anonymous>:4:307108)
>     at Object.loadAllAddons (<anonymous>:4:272224)
>     at Object.initialize (<anonymous>:4:266714)
>     at Object.initialize (<anonymous>:4:306318)
>     at Object.startup (<anonymous>:4:368333)
> ```
> 
> Fixed: #142

Thank you for the fix. However the problem still remains even after the update.

**Comment by MichaelDavidGK** [comment]
> 
> Thank you for the fix. However the problem still remains even after the update.

can you please confirm your plugin version is 1.2.1 and your zerespluginlibrary is 2.0?

**Comment by StepCenta** [comment]
> can you please confirm your plugin version is 1.2.1 and your zerespluginlibrary is 2.0?

Yes, i confirm that I have those versions

**Comment by MichaelDavidGK** [comment]
> Yes, i confirm that I have those versions
can you please turn it off and on in plugins?
does this error still show up in console while you turn the plugin on(ctrl+shift+i -> console tab)?

**Comment by StepCenta** [comment]
> > Yes, i confirm that I have those versions
> 
> can you please turn it off and on in plugins? does this error still show up in console while you turn the plugin on(ctrl+shift+i -> console tab)?

As I turn it off and on it regularly starts, no error comes on the console.
Plus I updated BD by mistake, now i have 1.4.0, I hope this doesn't mess up anything...

**Comment by StepCenta** [comment]
> As I turn it off and on it regularly starts, no error comes on the console. Plus I updated BD by mistake, now i have 1.4.0, I hope this doesn't mess up anything...

I just realized that there are different errors, all similar, but they don't come up when i switch the plugin on and off.

They look very similar and they all start like this: "DevTools failed to load source map: Could not load content for" and then different 404 errors.

Sorry if I don't understand a lot, I reached on GitHub for some support even if I don't know how to code (yet)

**Comment by MichaelDavidGK** [comment]
Those errors don't matter.
If you turn it on and there is no error it should work just fine.
It works for me:
![image](https://user-images.githubusercontent.com/39009683/150864376-f1e886d2-fb75-48fb-89ca-3b024d830ab8.png)

**Comment by StepCenta** [comment]
Yes, it works just fine, the problem is that I have to manually turn it off and on again everytime I open the discord app. Since I am not the only person using my PC (multiple Windows users) and i shut it down many times per day it can be quite annoying

**Comment by FearNaBoinne** [comment]
Same here... Currently on v1.2.2 (and Zeres 2.0), but it only loads if I disable/re-enable it. Not on app load or Ctrl-R.

**Comment by MichaelDavidGK** [comment]
1.2.2 should have fixed this.
Can you please reload(ctrl+r) and right press in text area (it might not work on 1st right press so try 2-3 times)?
If you don't get menu then please let me know what other plugins you have (can be screenshot from settings -> plugins) and if possible send me an error log from console.
> ctrl+shift+i, if on stable you will need to add this:
> "DANGEROUS_ENABLE_DEVTOOLS_ONLY_ENABLE_IF_YOU_KNOW_WHAT_YOURE_DOING": true,
> to your %appdata%/discord/settings.json
> make sure it looks like below or similar
![image](https://user-images.githubusercontent.com/39009683/151774065-1918e629-7f32-42d4-a6f6-5bae6f2ba478.png)

**Comment by FearNaBoinne** [comment]
It shows up at the 3rd right click... Weird, but now I know, I'll just re-click! ;)

**Comment by StepCenta** [comment]
It works fine for me too! 2nd or 3rd click do the trick!
