### ISSUE TITLE
[BUG] UserVolumeBooster not functioning properly

### ISSUE THREAD

**Issue by XiCynx** [QWERTxD/BetterDiscordPlugins#135]
After enabling the plugin and making sure the 0plugin is also enabled, when I click on a user, the volume slider only goes up to 200% still and nothing farther. Tried it with all 5 multipliers and it doesn't seem to function properly no matter which one is selected.

**Comment by MichaelDavidGK** [comment]
Fixed:
https://github.com/QWERTxD/BetterDiscordPlugins/pull/144
