### ISSUE TITLE
[BUG] Assign Badges  not working  I'm getting a build error

### ISSUE THREAD

**Issue by yunusbeyy** [QWERTxD/BetterDiscordPlugins#137]
**Describe the Bug**

**To Reproduce**

**Expected Behavior**

**Screenshots**

**Discord Version**

**Additional Context**

**Comment by MichaelDavidGK** [comment]
Works just fine, try redownloading and make sure you have latest ZeresPluginLibrary (2.0.0)

**Comment by papiIIonn** [comment]
I have latest ZeresPluginLibrary (2.0.0) and still not working at this my friend

AssignBadges: Could not be constructed.
    at Object.initializeAddon (<anonymous>:4:307996)
    at Object.loadAddon (<anonymous>:4:269972)
    at Object.loadAddon (<anonymous>:4:307108)
    at FSWatcher.<anonymous> (<anonymous>:4:267831)

**Comment by MichaelDavidGK** [comment]
Can you please check this:
https://github.com/MichaelDavidGK/BetterDiscordPlugins/blob/development/AssignBadges/AssignBadges.plugin.js

Let me know if it works for you

**Comment by papiIIonn** [comment]
![image](https://user-images.githubusercontent.com/79100577/150664345-11183641-4871-4e3a-88ca-079898d55b79.png)
its working but now i cant use it, i mean there is no "badge" option

**Comment by papiIIonn** [comment]
Ok my bad never mind i just forgot to copy a words

**Comment by Mo9nikeypurple** [comment]
i can not get it working to it just says An error was encountered while trying to load this plugin.
