### ISSUE TITLE
UserVolumeBooster is broken (probably due to last big internal Discord update)

### ISSUE THREAD

**Issue by Enrico9431** [QWERTxD/BetterDiscordPlugins#138]

**Comment by MichaelDavidGK** [comment]
dup of:
https://github.com/QWERTxD/BetterDiscordPlugins/issues/135

fixed:
https://github.com/QWERTxD/BetterDiscordPlugins/pull/144

**Comment by Enrico9431** [comment]
Can't use the slider to increase other's volume like before. Am only able to boost people above 200% using Zerthox BetterVolume plugin and manually filling in a certain value

**Comment by MichaelDavidGK** [comment]
Version 1.0.1?

**Comment by Enrico9431** [comment]
Apparently not, even though it did ask me to update a few days a ago

**Comment by MichaelDavidGK** [comment]
Then please download it and check, if fixed pls close the issue:
![image](https://user-images.githubusercontent.com/39009683/150864066-c3a74b89-f2f1-4f5f-b151-a78bfd743747.png)

**Comment by Enrico9431** [comment]
Downloaded 1.0.1 and now it works.
