### ISSUE TITLE
[Feature Request] [InAppNotifications] Add a "disable OS notification" settings

### ISSUE THREAD

**Issue by mutageneral** [QWERTxD/BetterDiscordPlugins#14]
I am suggesting being able to make discord not use the OS notification (like the native notification in Windows 10 by examples) at all time (not just in DND). This toggle would basically let the user replace the notification system completely with the one implemented in the add-on. I personally hate the Windows 10 notifications and would rather use this add-on. But even tho turning on DND with the add-on get pretty close to what I want (no win10 notifs), I lose the discord notification sound and I appear as DND to other which is not what I want to appear as all the time. I think making a button that will suppress OS notifications which will let me use the add-on with the online status to get no win 10 notifs but still getting the discord notification sound and by using the already existing "disable on do not disturb" it will act just like normal discord and let me easily mute it when I start a game or a group chat is being annoyingly active. Thank you for the consideration.

**Comment by QWERTxD** [comment]
This plugin is about notifications **inside** of Discord, not outside app notifications.

**Comment by QWERTxD** [comment]
Discord does not push Windows 10 Notifications while the app is focused.

**Comment by mutageneral** [comment]
Most people including me will not be focused in discord all the time. I personally have discord on a second crappy monitor and I think it is a pretty common thing to do, my friend also does that. When I get a notification I would like being able to just turn my head very slightly and see the notification inside of discord and not have the ugly annoying Windows 10 notification that takes soooo long to get off the screen, even more if someone sends more than one message in a row.

**Comment by QWERTxD** [comment]
Then disable this setting in Discord, this is not related to my plugin.
Go to User Settings -> Notifications, then switch off the "Enable Desktop Notifications".
