### ISSUE TITLE
Broke upon load. 

### ISSUE THREAD

**Issue by TsynkZZZ** [QWERTxD/BetterDiscordPlugins#141]
**Describe the Bug**
Does not compile. 

**To Reproduce**
Just drop in the plugins folder and try to use it. 

**Expected Behavior**
To compile. 

**Screenshots**
https://cdn.discordapp.com/attachments/606695601501110281/934590137101324390/unknown.png

**Discord Version**
Stable 111699 (e8f9fb9)
BetterDiscord 1.3.0

**Additional Context**
Completely broken, loaded it up after updating to ZeresPluginLibrary v2.0.0, starting throwing errors, I updated it to the recent version, now it won't even compile, quit Discord, brought it back up, nope, still broken beyond repair. 
https://cdn.discordapp.com/attachments/606695601501110281/934591461901598790/unknown.png
That screenshot there will show what it was doing after updating the ZeresPlugin before updating the plugin to the current version.

**Comment by SmolAlli** [comment]
The plugin works fine, please try to delete the plugin and re-download it. Reloading with ctrl/cmd r is also highly recommended after doing so.

**Comment by TsynkZZZ** [comment]
> The plugin works fine, please try to delete the plugin and re-download it. Reloading with ctrl/cmd r is also highly recommended after doing so.

https://cdn.discordapp.com/attachments/606695601501110281/934617377742663710/unknown.png 

Nope! Closed Discord out before redownloading and replacing with the one that's on GitHub. Still no dice.

**Comment by TsynkZZZ** [comment]
> The plugin works fine, please try to delete the plugin and re-download it. Reloading with ctrl/cmd r is also highly recommended after doing so.

After taking a look in the BD server, there was a fix in there, however, the one on GitHub isn't the fixed version and will cause a compiling issue. 

https://cdn.discordapp.com/attachments/688983122334842968/934620272638722098/unknown.png

**Comment by MichaelDavidGK** [comment]
Fixed and merged on main tree
