### ISSUE TITLE
[BUG] TypingUsersAvatars crowd themselves

### ISSUE THREAD

**Issue by ArcWandx86** [QWERTxD/BetterDiscordPlugins#150]
**Describe the Bug**
When a user is typing, the avatar is placed without creating more space for the username, causing it to split into 2 lines.

**To Reproduce**
Enable the plugin. Watch someone start typing.

**Expected Behavior**
Both avatar and username should appear in the same line.

**Screenshots**
![image](https://user-images.githubusercontent.com/57409597/150685839-abc35b88-684a-4f14-a559-8c5403c6f11f.png)

**Discord Version**
Stable

**Comment by MichaelDavidGK** [comment]
Plugin version 1.0.3?

**Comment by ArcWandx86** [comment]
Well, this is embarrassing lol. My bad.

I assumed the plugin would auto update, but it didn't. Welp, fixed.
