### ISSUE TITLE
[BUG] UserVolumeBooster is not working

### ISSUE THREAD

**Issue by BlueStarBRS** [QWERTxD/BetterDiscordPlugins#155]
**Describe the Bug**
you can no more set any volume over 200% 

**To Reproduce**
go on user try to make him louder but you will see its only 200%

**Expected Behavior**
that i can boost up the people like before with 400% 

**Screenshots**
![image](https://user-images.githubusercontent.com/25110093/150861752-3a79ee6f-4f32-44d7-a6ba-0cc0fdad0dce.png)
![image](https://user-images.githubusercontent.com/25110093/150861592-8d7fb24f-f853-4c8f-a58e-8004b8bb9f09.png)

**Discord Version**
![image](https://user-images.githubusercontent.com/25110093/150861805-d3a8fc47-3ccf-402c-ae5a-f8a7a679c213.png)

**Additional Context**
pls make it work again its one of my best plugins man

**Comment by dominikd1977** [comment]
Discord updated, wait for the plugins to update.

**Comment by MichaelDavidGK** [comment]
update plugin to 1.0.1

**Comment by BlueStarBRS** [comment]
[i fixed it self with this website](https://laynetheepic.github.io/projects/pc-theme-converter/) idk where you find a 1.0.1 there is still only a 1.0 (updated last time 8 months ago)

**Comment by MichaelDavidGK** [comment]
![image](https://user-images.githubusercontent.com/39009683/150872138-2c1b178a-5c6e-4b88-8712-265d3eb753da.png)
https://github.com/QWERTxD/BetterDiscordPlugins/tree/main/UserVolumeBooster

**Comment by BlueStarBRS** [comment]
> ![image](https://user-images.githubusercontent.com/39009683/150872138-2c1b178a-5c6e-4b88-8712-265d3eb753da.png) https://github.com/QWERTxD/BetterDiscordPlugins/tree/main/UserVolumeBooster
> 
> you most likely checked development tree instead of main tree

 also it will be not bad if the file on plugin repo get also updated and thank you

**Comment by MichaelDavidGK** [comment]
> also it will be not bad if the file on plugin repo get also updated and thank you

It needs to be done by DevilBro or his script
Nobody here can do that
