### ISSUE TITLE
[BUG] TypingUsersAvatar

### ISSUE THREAD

**Issue by abinroy04** [QWERTxD/BetterDiscordPlugins#159]
User Avatar is shown twice.
![image](https://user-images.githubusercontent.com/85763004/151300208-1ad992d1-1df7-4f17-b3e4-2e6d16dff4d0.png)

Plugin version: 1.0.3
Stable 112102 (7b5adfa)
BetterDiscord 1.4.0
Host 1.0.9003 Windows

**Comment by MichaelDavidGK** [comment]
Plugin version 1.0.3?
Any other plugins/themes that might be showing avatars?

What discord Version?

- Latest:
- Stable 111881 (859d8e9)
- BetterDiscord 1.4.0
- Host 1.0.9003
-

**Comment by MichaelDavidGK** [comment]
Sorry, I haven't seen you edited it.
What theme are you using?
Any other plugins that might also show avatars (like avatars everywhere)?

**Comment by abinroy04** [comment]
Theme: Comfy, not using anything that deals with avatars

**Comment by MichaelDavidGK** [comment]
Can you upload your plugins and themes folder?
And let me know if there are any that you have disabled so I try this the same way you do ;)

**Comment by abinroy04** [comment]
It seems like I can't attach the files here, even as zip... would you like me to contact you in discord or just say the names of the plugins I use ?

**Comment by MichaelDavidGK** [comment]
> It seems like I can't attach the files here, even as zip... would you like me to contact you in discord or just say the names of the plugins I use ?

If you are on the server then you can find me there under Contributor role, otherwise:
[Discord Server](https://discord.gg/xtuMrVH5)
