### ISSUE TITLE
[BUG] QuickMessages is now causing high CPU usage.

### ISSUE THREAD

**Issue by ItMeSarah** [QWERTxD/BetterDiscordPlugins#166]
**Describe the Bug**
QuickMessages is now using 20-25% more  CPU usage due to the newly put in await getSlateTextAreaContextMenu(); which scans every webpack module every milisecond (as Zerebos said it.)  until the user right clicks the slate text area and gets the context menu.

**To Reproduce**

Enable the plugin, restart discord, see CPU usage stay extremely high 20% higher than it should be. Right click the typing area 1-2 times to get the context menu and entry for quick messages, and CPU usage will go back down to the normal levels.

**Comment by rauenzi** [comment]
For additional context:

The lines in question are here https://github.com/QWERTxD/BetterDiscordPlugins/blob/main/QuickMessages/QuickMessages.plugin.js#L114-L122

I would highly recommend making use of the ZLibrary functions that do this in a much much more efficient way. You could simply change this line https://github.com/QWERTxD/BetterDiscordPlugins/blob/main/QuickMessages/QuickMessages.plugin.js#L174

to
```js
const SlateTextAreaContextMenu = await Library.DCM.getDiscordMenu("SlateTextAreaContextMenu");
```

this has the bonus that users will not need to right click multiple times for the new context menu entry to show up.

**Comment by MichaelDavidGK** [comment]
Fixed for both QuickMessages and GrammarCorrect:
https://github.com/QWERTxD/BetterDiscordPlugins/pull/167

Thanks for help @rauenzi 
Haven't get used to DCM yet
