### ISSUE TITLE
[FEATURE REQUEST] DndWhilePlaying

### ISSUE THREAD

**Issue by GerdBurger** [QWERTxD/BetterDiscordPlugins#182]
The ability to allow certain games to bypass the plugin 

Say im playing something i dont take seriously and i dont care about notifications, i could whitelist the game to bypass the dnd

**Comment by MichaelDavidGK** [comment]
Not possible with current code, plugin checks your status, if status is "in game" then it will go dnd.
maybe if it checked game names, but in this case we would need to add all games manually, which is not convenient either.

Unless u can make discord not display your status as "in game" then it's a nope

**Comment by GerdBurger** [comment]
Thanks for the reply. Sad it couldn't be done easily but understandable. Thanks for the awesome plugin tho!
