### ISSUE TITLE
[QuickMessages] Doesn't save line breaks

### ISSUE THREAD

**Issue by dav1312** [QWERTxD/BetterDiscordPlugins#2]
![image](https://user-images.githubusercontent.com/63931154/106763574-42824480-6637-11eb-9f14-4a6af9dff22b.png)
![image](https://user-images.githubusercontent.com/63931154/106763877-8f661b00-6637-11eb-854e-cab5c7ff63c9.png)

**Comment by QWERTxD** [comment]
Thanks for the report. Will be fixed

**Comment by QWERTxD** [comment]
just committed a new update with a fix.
