### ISSUE TITLE
Problem with microphone on plugin "User Volume Booster" 

### ISSUE THREAD

**Issue by LikeableMoneky** [QWERTxD/BetterDiscordPlugins#21]
I have noticed that i can only chnage the output volume (which works great even at 1000%, dont ask), but when it came to the microphone i couldn't change it past the default even on the 5x setting, it keeps jumping back to 100%. Thanks for reading!
![image](https://user-images.githubusercontent.com/56303654/119537612-e3d20980-bd92-11eb-9ebe-81932793cffb.png)

**Comment by QWERTxD** [comment]
this plugin is only for changing users volume, I will fix the bug that allows you to change mic volume, thank you
