### ISSUE TITLE
[BUG] The button to start activities is missing

### ISSUE THREAD

**Issue by dooder-codes** [QWERTxD/BetterDiscordPlugins#225]

**Comment by HypedDomi** [comment]
The Plugin is broken. From his server:
> As discord appears to be slowly rolling out Discord games  to all users, it is likely that DiscordActivities will be discontinued as there will be no use for the plugin unless we come up with something else for it.

**Comment by hecker12423** [comment]
its missing just like my dad!

**Comment by TrapStoner** [comment]
2 months later and they are STILL not publicly available.... Maybe fix the plugin in the meantime please??

**Comment by balu100** [comment]
+1

**Comment by friedthewires** [comment]
+3 My friends want it too.

**Comment by ciberjonaru** [comment]
+4

**Comment by Einhornyordle** [comment]
Well, he did it. He successfully delayed the update long enough for activities to become avalable for everyone. The issue can be closed and the plugin deleted now https://discord.com/blog/server-activities-games-voice-watch-together
