### ISSUE TITLE
[FEATURE REQUEST]Exclude words from being corrected (list in config)

### ISSUE THREAD

**Issue by SmRzT** [QWERTxD/BetterDiscordPlugins#238]
title

-For an example the term "brb" gets auto corrected to "barb" so it would be nice to exclude it from being corrected.
-Another Example is Names of things, I play Modded MC and mod names get auto corrected like the mod "pipez" gets corrected to "pipe"/"pipes"

**Comment by MichaelDavidGK** [comment]
just put it in quote then it's not gonna be corrected

nobody is working on plugins rn, so I doubt anyone will do it
