### ISSUE TITLE
CallTimeCounter resets time

### ISSUE THREAD

**Issue by monish-1234** [QWERTxD/BetterDiscordPlugins#24]
Hey ! Thanks for the wonderful plugin. I'm facing this issue from today. Whenever I move between servers, DMs or even between channels,  the Call counter (Time Elapsed) resets. Please look into it  :)

**Comment by Soitora** [comment]
Between Servers/DM/Channel as in the Voice channel or does it happen when you switch Text channel?

**Comment by z00rat** [comment]
switching text channel is enough to reset the timer 
and switching server and dm reset it too
going to **HOME** reset it too

**Comment by monish-1234** [comment]
> Between Servers/DM/Channel as in the Voice channel or does it happen when you switch Text channel?

Both. Everything.

**Comment by Soitora** [comment]
Not experiencing this issue.

Discord PTB 86407
BetterDiscord 1.1.1
CallTimeCounter v0.0.1

**Comment by MrFums** [comment]
+1, i have this issue as well on normal Discord client

**Comment by potatto99** [comment]
Same problem and I can also confirm that SpotifyControlPanel breaks the plugin, integration appreciated.
