### ISSUE TITLE
[SORTED]

### ISSUE THREAD

**Issue by Koskzk** [QWERTxD/BetterDiscordPlugins#241]
![image](https://user-images.githubusercontent.com/108202675/175831213-debbdb3f-017a-4dd3-b8ef-bbdd3178dd14.png)
Cant press nothing and the messages is not pasted

**Comment by Koskzk** [comment]
nwm found how to do :D

**Comment by HypedDomi** [comment]
can you close the issue then

**Comment by Koskzk** [comment]
how?

**Comment by HypedDomi** [comment]
on the bottom you have a close issue button

**Comment by HypedDomi** [comment]
Should look similar to this
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/50876016/175837267-256df4e8-c11f-4ab6-ba2e-ad181175e3d1.png">
