### ISSUE TITLE
typing users avatars crashes discord

### ISSUE THREAD

**Issue by HugoNotHere** [QWERTxD/BetterDiscordPlugins#25]
When the plugin was on it would crash my discord only when people were typing when the plugin was off it never crashed:
This is what crash recovery says: (unknown) [CrashRecovery] HEY OVER HERE! Show this to the plugin developer or in the support server!
Prettified stacktraces, stack:
 TypeError: Cannot read property 'startsWith' of undefined
    at AvatarComponent.render (<anonymous>:86:37)
    at <anonymous>:352:17 
Component stack:
     in AvatarComponent
    in div
    in strong
    in span
    in div
    in TypingUsers
    in FluxContainer(TypingUsers)
    in form
    in main
    in ForwardRef
    in LayerProvider
    in ChatLayerProvider
    in AnalyticsContext
    in ChannelChat
    in Unknown
    in div
    in div
    in Channel
    in Unknown
    in ChannelRenderer
    in t
    in RouteWithImpression
    in t
    in div
    in div
    in div
    in AppView
    in div
    in AnimatedComponent
    in Layer
    in div
    in TransitionGroup
    in Layers
    in ConnectedLayers
    in div
    in Shakeable
    in Chat
    in t
    in t
    in ViewsWithMainInterface
    in FluxContainer(ViewsWithMainInterface)
    in Suspense
    in d
    in t
    in t
    in div
    in ModalProvider
    in LayerProvider
    in VerificationLayerProvider
    in LayerProvider
    in AppLayerProvider
    in FocusRingScope
    in ErrorBoundary

**Comment by QWERTxD** [comment]
thats because you probably have PlatformIndicators

**Comment by FEDERICOMB96** [comment]
I have the same issue

**Comment by QWERTxD** [comment]
An update was pushed
