### ISSUE TITLE
[BUG] Assign Badge

### ISSUE THREAD

**Issue by Soulivan71** [QWERTxD/BetterDiscordPlugins#252]
**Describe the Bug**

1 => Bot verified badge are still bug in memberlist (bot and verified bot display)
2 => Verified bot doesn't appear in popout user

**To Reproduce**

Juste check memberlist and click on username

**Expected Behavior**

Just display verified bot

**Screenshots**

![image](https://user-images.githubusercontent.com/36502190/177788813-e76c36cb-80cc-4b90-8ad4-da9bbdc6a204.png)
![image](https://user-images.githubusercontent.com/36502190/177788869-0aa7a8b6-8b3e-4d45-99f1-b34dcab92c63.png)

**Discord Version**

Ptb 135383 (52cc282)

**Comment by HypedDomi** [comment]
Make sure youre on the latest Version which is 1.0.29 atm

**Comment by Soulivan71** [comment]
Yep I have the latest

**Comment by Soulivan71** [comment]
Im still having the issue btw just to notice

**Comment by Soulivan71** [comment]
![image](https://user-images.githubusercontent.com/36502190/182261092-2f7ec14c-9c4c-4571-bbaf-dcb900a277c0.png)
![image](https://user-images.githubusercontent.com/36502190/182261125-3f23fd79-7715-40e1-87ef-7667ce9ca9ac.png)
![image](https://user-images.githubusercontent.com/36502190/182261210-d6e3fd0a-4798-437f-8c4a-2bfe59326f33.png)
Is there somthing to fix it ?

**Comment by Soulivan71** [comment]
Do u found a fix ?
