### ISSUE TITLE
Another Crashing issue with TypingUsersAvatar

### ISSUE THREAD

**Issue by UltraBlackLinux** [QWERTxD/BetterDiscordPlugins#26]
Hey, there,
I just crashed because of TypingUsersAvatar:
![Screenshot_2](https://user-images.githubusercontent.com/62404294/120065005-7a424b80-c06f-11eb-8b12-4b934b8d97f1.png)

Are you able to fix this?
Thanks!

**Comment by QWERTxD** [comment]
You are not using the latest version of the plugin. Make sure to install the latest version because this issue is fixed there.

**Comment by UltraBlackLinux** [comment]
> You are not using the latest version of the plugin. Make sure to install the latest version because this issue is fixed there.

I just got the update today, since then I am having this crash lol

**Comment by QWERTxD** [comment]
You didn’t. The new file doesn’t include .startsWith at all.

**Comment by UltraBlackLinux** [comment]
> You didn’t. The new file doesn’t include .startsWith at all.

Weird? I clicked update, but I guess BD didn't want to

**Comment by UltraBlackLinux** [comment]
I don't know, why it didn't want to, but after reinstalling, it now does work, Thanks for your help.
