### ISSUE TITLE
Call time counter resetting when switching text channels

### ISSUE THREAD

**Issue by Ikaunieksplay** [QWERTxD/BetterDiscordPlugins#27]
https://user-images.githubusercontent.com/48332128/120165182-f79ec500-c203-11eb-9dc5-39c98bc7549b.mp4

**Comment by QWERTxD** [comment]
Are you using bdfdb?

**Comment by Dschogo** [comment]
Same for me, using bdfdb

**Comment by QWERTxD** [comment]
BDFDB causes this. Anyways there's an issue opened for that already.

**Comment by QWERTxD** [comment]
Oh oops there’s no issue opened for that 😬

**Comment by cilgintebesir** [comment]
Same for me

**Comment by QWERTxD** [comment]
Already said that it’s because of Bdfdb

**Comment by Ikaunieksplay** [comment]
Right so is there any fix? Or do I just have to disable BDFDB and deal with it?

**Comment by dav1312** [comment]
It's caused by Spotify Controls
