### ISSUE TITLE
[BUG] DndWhilePlaying - Status Not Being Set

### ISSUE THREAD

**Issue by SnakerBone** [QWERTxD/BetterDiscordPlugins#284]
**Describe the Bug**
Status is not being set when I play a game

**Expected Behavior**
It should set to Dnd

**Screenshots**
![image](https://user-images.githubusercontent.com/55041473/191892031-76a4d016-ac59-470a-89b7-c80612af46b2.png)

**Discord Version**
Stable

**Comment by NihatSuleymanov-GitHub** [comment]
I have the same issue.
