### ISSUE TITLE
Avatars not showing in inAppNotifications plugin

### ISSUE THREAD

**Issue by re11ding** [QWERTxD/BetterDiscordPlugins#29]
Title says it all. The plugin works, but avatars do not appear.

**Comment by voidfill** [comment]
from qwert 3-ish days ago 
![image](https://user-images.githubusercontent.com/71205200/120558349-9a6f6300-c3ff-11eb-869a-d6251944f16d.png)

**Comment by re11ding** [comment]
Oh, excellent thank you! No need to keep this open then.
