### ISSUE TITLE
[QuickMessages] Adds line breaks when is not supposed to

### ISSUE THREAD

**Issue by dav1312** [QWERTxD/BetterDiscordPlugins#3]
Message that should save
![image](https://user-images.githubusercontent.com/63931154/109392614-6296e200-791d-11eb-90aa-ee4d08078818.png)

Saved message
![image](https://user-images.githubusercontent.com/63931154/109392623-77737580-791d-11eb-9008-c32f1be5c11f.png)

Config
![image](https://user-images.githubusercontent.com/63931154/109392629-80644700-791d-11eb-9ff1-29a500c1c6e9.png)

**Comment by QWERTxD** [comment]
An update is ready 👌🏻 
Pushing it and an update bar should automatically pop up when the update is ready.

**Comment by QWERTxD** [comment]
Thank you for your report, just pushed the fixing update 👌🏻
