### ISSUE TITLE
[BUG] InAppNotifications no longer works in BD 1.8.0

### ISSUE THREAD

**Issue by sludgepudge** [QWERTxD/BetterDiscordPlugins#302]
**Describe the Bug**
In the newest BD release (1.8.0), InAppNotifications no longer works again.

**To Reproduce**
Enable plugin and see error in top right corner.

**Expected Behavior**
No errors and notifications as usual.

**Screenshots**
![G1kSJD9wfA](https://user-images.githubusercontent.com/55224159/195185814-d268a12e-f280-4b11-a6ed-cce86c00ee78.png)
![Discord_xlDYx7lSso](https://user-images.githubusercontent.com/55224159/195185826-f3ba8fe9-156e-4d0d-a8d2-62d1ef1a297d.png)

**Discord Version**
Stable 151857

**Additional Context**
Was working fine in BD 1.7.0, updated to 1.8.0 as it reverts some changes the BD team made after Discords huge update. I fully expect that some plugins that were fixed would again be broken but making this bug report to assist getting the plugin usable again!

**Comment by nefariouslegion** [comment]
Same issue here. But my console also shows some errors about renaming the file for some reason? Says no file found even though I didn't delete it
![image](https://user-images.githubusercontent.com/89366675/195214263-03cd2e95-3589-4352-abbd-1558e8b75e9e.png)

**Comment by RuneDemomn** [comment]
same issue

**Comment by ZeddPerm** [comment]
+1

**Comment by pp0236** [comment]
++

**Comment by IAMMASTERBAITER** [comment]
+

**Comment by BlackLightX** [comment]
+

**Comment by TempAccountNull** [comment]
this

**Comment by mrmiller110586** [comment]
same issue man i feel so lost without this and i am missing so many things now. man i would pay for this feature if i could ngl. man if you have the time and can fix it i would be so appreciative

**Comment by Xelus22** [comment]
Its not just betterdiscord that was broken. Discord pushed huge API changes which means that a lot (almost all) of plugins are also broken (almost every plugin in this repo is broken). If you really want this feature then code or fix this plugin yourself or be patient with QWERTxD when they have time to come back and fix all the plugins slowly.

**Comment by sludgepudge** [comment]
> 

Yes, I'm aware of that and I referred to that in my initial post. BD pushed 1.7.0 to remedy the huge update that Discord pushed and InAppNotifications (with ZeresLibrary) works fine in version 1.7.0 of BD.

However, one of the changes BD made in their haste to get the package working again has since been reverted in the 1.8.0. Now, some of the plugins that were fixed (like InAppNotifications), are now broken yet again in 1.8.0.

**Comment by Xelus22** [comment]
I see. Looks like one of the issues is here on line 926.

https://github.com/QWERTxD/BetterDiscordPlugins/blob/main/InAppNotifications/InAppNotifications.plugin.js#L926

Which is  gotten from line 216
https://github.com/QWERTxD/BetterDiscordPlugins/blob/main/InAppNotifications/InAppNotifications.plugin.js#L216

So it seems "GUILD_TEXT" has been changed or something? But im not sure what to.

**Comment by sludgepudge** [comment]
There's a handle of issues, I've tried to work through them, but I have a lot of other projects to work on at the moment.

Simply opened this issue so it's logged and if/when someone can look into it, they can.

**Comment by Xelus22** [comment]
This works now. HOWEVER this is still a BUG which does NOT mark the message as read after closing the notification. 
I also experienced that if BD is open for long amounts of time, BD will still crash.
I am unsure whose fault that is but at least this currently works for now.

https://gist.github.com/Xelus22/25e468d9702e3ac9054d064c2fb5f9dd

**Comment by DaEnder** [comment]
those are some very annoying error notifs.....

**Comment by sludgepudge** [comment]
Fixed in 1.1.1
