### ISSUE TITLE
Code creates voiceTimer div using the render() method

### ISSUE THREAD

**Issue by rarescolibaba** [QWERTxD/BetterDiscordPlugins#32]
According to [this diagram](https://projects.wojtekmaj.pl/react-lifecycle-methods-diagram/), the `render()` method should only be used "purely".
From the [documentation](https://reactjs.org/docs/react-component.html#render):

> The `render()` function should be pure, meaning that it does not modify component state, it returns the same result each time it’s invoked, and it does not directly interact with the browser.
> If you need to interact with the browser, perform your work in `componentDidMount()` or the other lifecycle methods instead. Keeping `render()` pure makes components easier to think about.

Doesn't the code below interact with the browser by creating a `div` element?
https://github.com/QWERTxD/BetterDiscordPlugins/blob/50fb577359f2f48e5307dac7c5e00ab9b6cffcb8/CallTimeCounter/CallTimeCounter.plugin.js#L96-L99

**Comment by QWERTxD** [comment]
The timer element updates everytime the state changes
