### ISSUE TITLE
[BUG] CallTimeCounter resets time when clicking a DM notification

### ISSUE THREAD

**Issue by Frontear** [QWERTxD/BetterDiscordPlugins#321]
**Describe the Bug**
When you get a DM notification in the top right, clicking on it will apparently clear your call time count, resetting back to 0.

**To Reproduce**
Get a DM notification
Click it while being in a call in a different server/dm

**Expected Behavior**
The call time remains untouched

**Screenshots**

**Discord Version**
Stable

**Additional Context**

**Comment by shamshitty** [comment]
im getting this when opening an unread channel in servers too
