### ISSUE TITLE
HidePerServerAvatars

### ISSUE THREAD

**Issue by MoDerPo** [QWERTxD/BetterDiscordPlugins#33]
Is this an out of season april fools joke?
I've never heard of per server avatars... did I miss something???

**Comment by QWERTxD** [comment]
Do you think that a joke plugin would get approved?

**Comment by CeSeT** [comment]
then how can I set my avatar to be specific to a server?

**Comment by QWERTxD** [comment]
![image](https://user-images.githubusercontent.com/77858402/121017994-95673680-c7a6-11eb-929a-511740e9d25c.png)

**Comment by CeSeT** [comment]
I can'tsee such an option, is it because that is not discord canary or is there another plugin I need to add?

**Comment by QWERTxD** [comment]
Currently it's a closed beta, soon discord will release it to all of the users

**Comment by CeSeT** [comment]
I understand 
but i think you should state it in the description because anyone who sees the plugin in the store will be curious about that

**Comment by MoDerPo** [comment]
exactly
