### ISSUE TITLE
[BUG] AppNotifications Plugin not working properly since most recent Discord Update

### ISSUE THREAD

**Issue by BoneDaddy1** [QWERTxD/BetterDiscordPlugins#376]
AppNotifications Plugin does not work since most recent update. It was working properly prior to the most recent update

No steps to reproduce

**Expected Behavior**
Notifications to display like before

Screenshots - N/A; no error on Plugin Details

Stable 230914 (96fc479) 
Host 1.0.9018 x86 (37684) 
Windows 10 64-Bit (10.0.22621)

Adding issue since Support Server is inactive

EDIT:
Sorry, I completely forgot to list the plugin that isn't working.

**Comment by yibbbbb** [comment]
plugin broken is app notifications btw
