### ISSUE TITLE
[QuickMessages] Emojis not saving

### ISSUE THREAD

**Issue by dav1312** [QWERTxD/BetterDiscordPlugins#4]
_(yes, its me again lol, sorry)_

Emojis are not saved properly
![image](https://user-images.githubusercontent.com/63931154/109436251-f00e2b00-7a1e-11eb-920d-090d9d127fd9.png)
![image](https://user-images.githubusercontent.com/63931154/109436262-0916dc00-7a1f-11eb-80f9-bc7dbfa9055b.png)
![image](https://user-images.githubusercontent.com/63931154/109436358-5e52ed80-7a1f-11eb-9593-13fa1c1d3854.png)

**Comment by QWERTxD** [comment]
Thank you for reporting. I'll check this issue.

**Comment by QWERTxD** [comment]
I just launched v1.1 which includes a few new updates including a fix for the bug you found!
Thank you for reporting! 😄

**Comment by QWERTxD** [comment]
Are you \_david_ from BD Support Server?

**Comment by dav1312** [comment]
yes 🙃

**Comment by HellDeadShot** [comment]
how to save message in this plugin?
