### ISSUE TITLE
Suggestion for Global Replies

### ISSUE THREAD

**Issue by fukuimaunicorn** [QWERTxD/BetterDiscordPlugins#40]
Hey, I really love your global replies plugin and its a feature that I always wanted in Discord. But wouldn't it make sense to include the message link somehow, as it does the same in discord as an actual reply, even cross server. I don't know if there's a way to put a link in a message without having the big ugly message link, but it would actually highlight the mentioned message.

**Comment by QWERTxD** [comment]
That is the only way to do that, it's impossible to post Inline Replies outside of the message's original channel
