### ISSUE TITLE
Suggestion/Request for DNDWhilePlaying

### ISSUE THREAD

**Issue by ZinniaBelle** [QWERTxD/BetterDiscordPlugins#44]
Please add the ability to blacklist certain games, some games require more focus than others while others are more relaxed, the ability to turn it off on certain games would be helpful.

**Comment by Glaived** [comment]
A blacklist + whitelist system would be really interesting, with another option to stipulate if you want to activate the blacklist, or the whitelist, or neither

**Comment by RadNotRed** [comment]
You can turn off game status's for certain games but maybe it will come in the future
