### ISSUE TITLE
Stop counting time while on deafen

### ISSUE THREAD

**Issue by OsoaGitHub** [QWERTxD/BetterDiscordPlugins#46]

**Comment by RadNotRed** [comment]
I do not see a point in this.

**Comment by OsoaGitHub** [comment]
Wait, hold on. The point of this is that it would show how long you have actually been talking instead of how long you’ve been in the call for

**Comment by RadNotRed** [comment]
but that's the point of CALL TIME COUNTER not TALK TIME COUNTER

**Comment by OsoaGitHub** [comment]
Hmm, I guess that's true. maybe at least an option though?
