### ISSUE TITLE
Feature Request - AssignBadges - Change Tooltip Date of certain Badges

### ISSUE THREAD

**Issue by GoldenMyst** [QWERTxD/BetterDiscordPlugins#53]
![Screenshot_44](https://user-images.githubusercontent.com/74118946/123720049-f7f8a300-d837-11eb-8649-c3cd48c14c61.png)
![Screenshot_45](https://user-images.githubusercontent.com/74118946/123720054-f929d000-d837-11eb-888b-a5d5e061b272.png)

**Comment by QWERTxD** [comment]
You can also change the boost badge.
