### ISSUE TITLE
[Bug] - AssignBadges - Reset Boost Preferences button doesn't work

### ISSUE THREAD

**Issue by Apceniy** [QWERTxD/BetterDiscordPlugins#54]
When I click that button, it says that it succesfully cleared boost preferences, but nothing actually happens. In order to do that, I need to reset all the preferences at once.

**Comment by QWERTxD** [comment]
It does work for me 🤷🏻

**Comment by Apceniy** [comment]
https://user-images.githubusercontent.com/53149450/123766123-70627100-d8d7-11eb-9239-f4783611a9c7.mp4


https://user-images.githubusercontent.com/53149450/123766126-722c3480-d8d7-11eb-9480-5ca572f0505b.mp4

**Comment by QWERTxD** [comment]
Make sure to install the latest version from https://betterdiscord.app/
