### ISSUE TITLE
[Typingindicator] Issue: crash when clicked 

### ISSUE THREAD

**Issue by nexioss** [QWERTxD/BetterDiscordPlugins#58]
**Describe the bug**
when someon is tiping on the chat and click on the pfp discord just chow a error and need to restart

**To Reproduce**
1.someon tiping on chat
2. Click on the pfp to the botom of the text bar

**Expected behavior**
do nothing, or chow the user profile

**Screenshots**

https://user-images.githubusercontent.com/86494178/123563044-a65a0500-d7b2-11eb-92fc-b2299dd01ea8.mp4

**Information**
 - OS: wndows 10 21H1
 - 1.0.2
 - Stable 88979 (c845aa2)

**Additional context**
none

**Comment by QWERTxD** [comment]
It’s a Zlib bug, it might take some time until zere updates it

**Comment by nexioss** [comment]
tanks, cause the nam was rhong
