### ISSUE TITLE
[SUGGESTION] InAppNotifications: Resize notification windows.

### ISSUE THREAD

**Issue by zenkarus** [QWERTxD/BetterDiscordPlugins#59]
As the title suggest, an option to resize the toast notification windows would be a great improvement to be added. I do understand however if this is not a priority for you to implement. Thank you.

**Comment by ItsCubeTime** [comment]
I think this is a good idea, I do personally think that they are just a little small at the moment. Would also be cool if one could adjust the color to make them a little more obvious

Like the op said, I would also understand if this is not a priority.

**Comment by RadNotRed** [comment]
may not happen due to toast limitations
