### ISSUE TITLE
suggestion for AssignBadges

### ISSUE THREAD

**Issue by FrostbearDeluxe** [QWERTxD/BetterDiscordPlugins#60]
**Custom Badges:** _It would consist of a special menu where you upload images from your PC to convert them into badges, you put the name, the description when hovering the mouse over it and the link to the web page to which it will send you if you click it (the latter would be optional)_

**Server Badges:** _This would be smaller but just as functional, they would be the boost level badges, partner server, verified server, etc. only functional for servers_

**Unverified Bot Tag:** _The classic not verified bot tag, it could also help to easily solve the error of the verified bot tag in users who when using it gives you a normal not verified bot tag and you cannot remove it until you restart discord_

**Webhooks Badges:** _the truth the name says, the ability to add badges to webhooks_

And that would be all, I would appreciate it very much if you could add all this and excuse me if it is a lot of work xd

**Comment by Skriptic** [comment]
I agree on this 100%

**Comment by Overimagine1** [comment]
It would be more productive and less cluttered to give a thumbs up reaction instead of commenting “i agree”.

**Comment by voidfill** [comment]
> It would be more productive and less cluttered to give a thumbs up reaction instead of commenting “i agree”.

i agree

**Comment by Skriptic** [comment]
> **Custom Badges:** _It would consist of a special menu where you upload images from your PC to convert them into badges, you put the name, the description when hovering the mouse over it and the link to the web page to which it will send you if you click it (the latter would be optional)_
> 
> **Server Badges:** _This would be smaller but just as functional, they would be the boost level badges, partner server, verified server, etc. only functional for servers_
> 
> **Unverified Bot Tag:** _The classic not verified bot tag, it could also help to easily solve the error of the verified bot tag in users who when using it gives you a normal not verified bot tag and you cannot remove it until you restart discord_
> 
> **Webhooks Badges:** _the truth the name says, the ability to add badges to webhooks_
> 
> And that would be all, I would appreciate it very much if you could add all this and excuse me if it is a lot of work xd

I agree

**Comment by RadNotRed** [comment]
lightcord may be able to help you
