### ISSUE TITLE
[feature request] [inAppNotifications] Allow the notifications to be displayed even outside of the Discord window?

### ISSUE THREAD

**Issue by ItsCubeTime** [QWERTxD/BetterDiscordPlugins#63]
Hi there, regular Windows toaster notifications havent worked for me for years (they simply dont show up), Ive been in touch with Discords support several times and searched for answers everywhere (followed plenty of guides on potential fixes).

Your plugin however works on my device! Its just that I would also like to be able to see the notifications even if Discord is not topmost. If possible even over fullscreen applications.

**Comment by QWERTxD** [comment]
it is impossible since betterdiscord is being injected to the client and not to your system

**Comment by RadNotRed** [comment]
lightcord may be able to help you

**Comment by ItsCubeTime** [comment]
> lightcord may be able to help you

I just tried installing it with the installer downloadable from there github releases. No notifications from Lightcord either.

> it is impossible since betterdiscord is being injected to the client and not to your system

There are also libraries like this https://www.npmjs.com/package/node-notifier

But I suppose this might only be useful for me and no one else

**Comment by ItsCubeTime** [comment]
I dont actually know JS. Im half-a-year beginner in C and C++ but I looked a little at the code and I think I could build myself a solution by modifying your code a little.

Would it be as simple as replacing all the occurances of QWERTLib.Toasts.create() with some other method for sending the notifications? Or is there some "send" method somewhere or other things I need to be aware of?

**Comment by ItsCubeTime** [comment]
I would have liked to also register and option in the plugin settings/configuration pane but, I probably shouldnt complicate things for myself 😋
