### ISSUE TITLE
error installing plugins

### ISSUE THREAD

**Issue by ismaelpoetacute** [QWERTxD/BetterDiscordPlugins#66]
hi, when I try to install the plugins I get the following error

UserVolumeBooster: Could not be constructed.
    at Object.initializeAddon (<anonymous>:4:230093)
    at Object.loadAddon (<anonymous>:4:192116)
    at Object.loadAddon (<anonymous>:4:229205)
    at FSWatcher.<anonymous> (<anonymous>:4:190100)

How can I solve this problem?

**Comment by BeardieTV** [comment]
Also seeing this issue with UserVolumeBooster with the following setup: Discord Stable 89709 (8d00f68), BetterDiscord 1.2.0, UserVolumeBooster 1.0.0

**Comment by RadNotRed** [comment]
Refresh Discord by pressing CTRL + R or if you're on Mac, ⌘ + R at the same time.
 If you get an error that is similar to "META not found", re-install the plugin, you probably have an empty plugin file.

**Comment by BeardieTV** [comment]
Same result, screenshot here:
https://i.imgur.com/gI0hBnQ.png

That's with a fresh download popped into the plugin directory as UserVolumeBooster.plugin.js

**Comment by QWERTxD** [comment]
You probably don't have ZLibrary installed. please make sure to have it before using any of my plugins.

**Comment by ismaelpoetacute** [comment]
Hello for those who have the same error as me, I solved it by installing the plugin from the plugin library, I leave the necessary plugin here https://betterdiscord.app/plugin/PluginRepo

**Comment by BeardieTV** [comment]
I'm still having issues with it, oh well.  Going to pass on the zLibrary installation.  Thanks though!
