### ISSUE TITLE
[BUG] QuickToggler not opening after shortcut changed

### ISSUE THREAD

**Issue by WIPocket** [QWERTxD/BetterDiscordPlugins#67]
**Describe the Bug**
Nothing happens when I press the new shortcut (no errors in console).

**To Reproduce**
Install (https://betterdiscord.app/Download?id=364), enable and set a non-default shortcut

**Expected Behavior**
*Something* should happen

**Discord Version**
Stable 90176 (337b0b5)
BetterDiscord 1.2.0
Host 0.0.15 Linux 64-Bit (5.10.0-7-Amd64)
QuickToggler 1.0.0

**Additional Context**
Tried multiple shortcuts, completely restarting Discord.
Also, the default works (after I remove the `QuickToggler.config.json` file) but shows up as this instead of Ctrl+D:
![image](https://user-images.githubusercontent.com/18397681/125933803-28e78b73-a1ce-491e-8507-14493dd5d88e.png)

**Comment by QWERTxD** [comment]
Can not reproduce

**Comment by RadNotRed** [comment]
Cannot reproduce
