### ISSUE TITLE
[BUG] TypingUsersAvatars doesn't use a user's server profile picture

### ISSUE THREAD

**Issue by EvelynProto** [QWERTxD/BetterDiscordPlugins#68]
**Describe the Bug**
TypingUsersAvatars doesn't use a user's server profile picture (if applicable)

**To Reproduce**
Get a friend with Discord Nitro to set their avatar to a different one for a single server.
Get them to start typing, the avatar shown while typing is their global profile picture, not the server one.

**Expected Behavior**
The profile picture shown should be the server one, or have a setting to change between having server profile pictures enabled or not.

**Screenshots**
![image](https://user-images.githubusercontent.com/54776821/125958498-add4d838-a832-4100-a52f-d2ac0cad0729.png)
![image](https://user-images.githubusercontent.com/54776821/125958516-6de49c71-945a-4027-8fa6-d376b2da7248.png)

**Discord Version**
Stable 90176

**Comment by RadNotRed** [comment]
All plugin updates halted.
