### ISSUE TITLE
Update for Threads

### ISSUE THREAD

**Issue by Masono03** [QWERTxD/BetterDiscordPlugins#73]
With discord adding threads can this plugin get updated so it works again since now servers that have threads basically make the plugin useless since it opens context menu wether to upload a pic or start a thread now :/

**Comment by QWERTxD** [comment]
what plugin are you talking about?

**Comment by Masono03** [comment]
Ah damn sorry I dunno how to properly use GitHub I thought it made the post specifically for the plug-in. I’m speaking of the “Old Upload” plugin.

**Comment by QWERTxD** [comment]
Works fine for me with threads.

**Comment by Masono03** [comment]
For me it opens the context menu again :/ I’m on newest canary.

**Comment by QWERTxD** [comment]
Make sure the plugin is enabled

**Comment by Masono03** [comment]
It is ^^’ I checked before coming here trust me I wouldn’t have come here otherwise lol

**Comment by Thespikedballofdoom** [comment]
same

**Comment by Masono03** [comment]
so i checked again to make sure i wasnt going crazy. heres a better explanation of whats wrong:

- oldupload works fine in servers that dont have threads, private convos & private groups
-servers that have threads activated already display a context menu as shown here [https://ibb.co/jvZZZdm](url)

thus would be great if the plugin was updated for servers that have threads and give the context menu since you can make threads at the top of discord as well so its useless having a second button on the upload button

**Comment by Thespikedballofdoom** [comment]
so can it be fixed?

**Comment by RadNotRed** [comment]
soon:tm:

**Comment by RadNotRed** [comment]
All plugin updates halted.
