### ISSUE TITLE
[BUG]Notifications from blacklisted servers are still being pushed with AppNotifications plugin

### ISSUE THREAD

**Issue by identity7** [QWERTxD/BetterDiscordPlugins#75]
**Describe the Bug**
A certain server I have blacklisted in the plugin settings still has notifications being pushed, even though its ID is blacklisted, as well as the messages not having any of the keywords I have in my config

**To Reproduce**
idk. Use discord I guess

**Expected Behavior**
I shouldn't be getting notifications from servers I have blacklisted

**Discord Version**
Stable 1.0.9002

**Additional Context**
AppNotifications plugin is version 1.0.0

**Comment by RadNotRed** [comment]
serverId, serverId2
