### ISSUE TITLE
[FEATURE REQUEST] call time counter

### ISSUE THREAD

**Issue by BlueStarBRS** [QWERTxD/BetterDiscordPlugins#76]
**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like**
- show only elapsed time if you hover over the call infobox 
- add a function to switch on and off for "if you dont hover on the call info box hide the elapsed time mode"

**Comment by RadNotRed** [comment]
Its called call time counter for a reason, its not "time you've hovered on the call info box" counter

**Comment by BlueStarBRS** [comment]
> Its called call time counter for a reason, its not "time you've hovered on the call info box" counter

what a really cheap argument 🤦🏻‍♂️

its rly smarter and saves space on tiny monitors or high scale clients mto hide it and only show it if you hover over the call box so pls 
da hell man

**Comment by RadNotRed** [comment]
Well, all plugins have stopped being updated.
