### ISSUE TITLE
[BUG] edited users are dont showing in the typing box

### ISSUE THREAD

**Issue by BlueStarBRS** [QWERTxD/BetterDiscordPlugins#78]
**Describe the Bug**
if you edit with the plugin editusers from Devilbro the avatar is not showing in the typing bar 

**To Reproduce**
use edit users plugin and edit someones name or profile pic etc. who then writing in the chat and you will see it does not work  

**Expected Behavior**
that i see the orriginal PB or the replaced avatar in the typing box

**Screenshots**
edited
![image](https://user-images.githubusercontent.com/25110093/128390872-100f3dc2-8c0c-423c-9901-588406fe5fc8.png)
not edited
![image](https://user-images.githubusercontent.com/25110093/128390895-8d4995f0-0ac0-4941-ba61-51da5bb84b6e.png)

**Discord Version**
last version

**Additional Context**
![image](https://user-images.githubusercontent.com/25110093/128390964-6804091c-a254-4a10-88d4-d79f46d2ebe7.png)
if you edit one of this stuff (not tag) the plugin dont work for the edited user.

**Comment by RadNotRed** [comment]
All plugin updates halted.

**Comment by BlueStarBRS** [comment]
Plugin: deleted.

RadNotRed ***@***.***> schrieb am Fr., 13. Aug. 2021, 08:07:

**Comment by RadNotRed** [comment]
thats fine, its not getting updated. its not qwerts fault devilbros shitty plugin doesnt work with it
