### ISSUE TITLE
[BUG] The new updated of this plugin is a mess

### ISSUE THREAD

**Issue by marcpinet** [QWERTxD/BetterDiscordPlugins#80]
**Describe the Bug**
Since yesterday (the last update), the plugin as been renamed. Furthermore, there are a bunch of bugs (notifications not appearing at all) that made me reinstall the plugin. Finally, least but not last: WHERE IS THE CENTER TOP OPTION ??? We can only have right and left notifications but not center like we had before. Furthermore, notifications now have a length depending of the message length which is graphically awful :/

**To Reproduce**
Nothing to reproduce

**Expected Behavior**
We could at least center notifcations on top like we could before (and like Xenolib does). Same length of notifcation for every messages even those which only contains a single character.

**Screenshots**
![image](https://user-images.githubusercontent.com/52708150/129201342-570b410b-7bf0-4668-b222-61f525a73d80.png)

**Discord Version**
Latest Stable

**Additional Context**
Please, understand that the best place for notifications is TOP CENTER and NOTHING ELSE for A LOT OF PEOPLE since it's the only one that does not hide clickable buttons when the notification is large (look at the picture, how can I click on the GIF or Emoji picker with the notification hidding it ?? It's non aesthetic)

**Comment by RadNotRed** [comment]
All plugin updates halted.

**Comment by marcpinet** [comment]
> All plugin updates halted.

What do you mean by halted? When will the plugin come back to normal?

**Comment by RadNotRed** [comment]
No plugins are being updated.

**Comment by marcpinet** [comment]
> No plugins are being updated.

Until when?

**Comment by marcpinet** [comment]
Nevermind, I just tweaker the CSS so it cames back to normal:

Here is the new file for those who are interested: 

[InAppNotifications.plugin.zip](https://github.com/QWERTxD/BetterDiscordPlugins/files/6983818/InAppNotifications.plugin.zip)

**Comment by marcpinet** [comment]
For those who prefers the old one, here the steps to reproduce:

1 - Close Discord (or it won't work)
2 - Delete every single file related to "InAppNotifcations" or "AppNotifications" in your plugin folder.
3 - Add those two files in your plugin folder: [InAppNotificationsFiles (Please unzip).zip](https://github.com/QWERTxD/BetterDiscordPlugins/files/6983862/InAppNotificationsFiles.Please.unzip.zip)
4 - Launch Discord and enable the plugin to make it work again!

**Comment by RadNotRed** [comment]
you could also just change it in settings

**Comment by RadNotRed** [comment]
and that InAppNotifications isnt even made by qwert

**Comment by marcpinet** [comment]
> you could also just change it in settings

No we can't since there is no "Top center" option...

**Comment by RadNotRed** [comment]
top center? wtf

**Comment by RadNotRed** [comment]
who tf uses top center

**Comment by RadNotRed** [comment]
just use top right

**Comment by marcpinet** [comment]
me xD

**Comment by marcpinet** [comment]
what u using?

**Comment by RadNotRed** [comment]
Ok then stick to lightys plugin, go complain to him

**Comment by RadNotRed** [comment]
i dont use the plugin

**Comment by RadNotRed** [comment]
join the discord read annoucements and support channel theres a whole thing on this
