### ISSUE TITLE
[BUG] Better Upload just doesn't work

### ISSUE THREAD

**Issue by Longtime4321** [QWERTxD/BetterDiscordPlugins#91]
When clicking the upload button, it still asks if I want threads or to upload.

Click the upload button.

Clicking the upload button brings up the file browser

![image](https://user-images.githubusercontent.com/40969041/131714363-6ceae987-58f8-4910-bbaf-468f17740272.png)

PTB

**Comment by RadNotRed** [comment]
or just.. join the discord and get the one from there lol
